name: SoulSMP
main: me.Evil.soulSMP.SoulSMP
version: 1.0.0
api-version: 1.20
author: Evil
description: Team-based SMP with banner claims and Soul Token currency.

commands:
  team:
    description: Team management command.
    usage: /team <create|info|leave|disband|banner|borders|invite>
    aliases: [t]
  tw:
    description: Send a message to your team.
    usage: /tw <message>
    aliases: [tm, teammsg, tsay, tmsg]
  tc:
    description: Toggle team chat mode on or off.
    usage: /tc
    aliases: [tchat, tctoggle, teamchat]