name: SoulSMP
main: me.Evil.soulSMP.SoulSMP
version: 1.0.0
api-version: 1.20
author: Evil
description: Team-based SMP with banner claims and Soul Token currency.

commands:
  team:
    description: Team management command.
    usage: /team <create|info|leave|disband|banner|borders|invite>
    aliases: [t]
  tw:
    description: Send a message to your team.
    usage: /tw <message>
    aliases: [tm, teammsg, tsay, tmsg]
  tc:
    description: Toggle team chat mode on or off.
    usage: /tc
    aliases: [tchat, tctoggle, teamchat]
  token:
    description: Admin command for managing Soul Tokens
    usage: /token give <player> <amount>
    permission: soulsmp.admin
    aliases: [st, stoken, soultoken]
  soulsmp:
    description: Primary SoulSMP command. Reload configs and spawn-building tools.
    usage: /soulsmp reload | /soulsmp text <create|edit|line|clear|info|done|cancel>
    permission: soulsmp.admin
    aliases: [ ssmp ]
  journal:
    description: Opens the Fishing Journal
    usage: /journal
    aliases: [ fj, fishingjournal ]
  store:
    usage: /store
    description: Open the player store.
  fishsim:
    description: Simulate fish generation and print score statistics + sell multiplier suggestions.
    usage: /fishsim [samples] [luck]
  bank:
    description: Open the Soul Token bank
    usage: /bank
  lb:
    description: Leaderboard admin
    usage: /lb <set|remove|recompute>
    permission: soulsmp.admin
