name: SoulSMP
main: me.Evil.soulSMP.SoulSMP
version: 2.1.0
api-version: 1.20
author: Evil
description: Team-based SMP with banner claims.

commands:
  ssmp:
    description: SoulSMP admin command.
    usage: /ssmp reload
    permission: soulsmp.admin
    aliases: [ soulsmp ]
  text:
    description: Spawn-building TextDisplay tools.
    usage: /text <create|edit|line|clear|info|export|import|done|cancel>
    permission: soulsmp.admin
  npc:
    description: Mannequin NPC tools (shop/bank).
    usage: /npc <create|remove|info>
    permission: soulsmp.admin
  team:
    description: Team management command.
    usage: /team <create|list|info|leave|disband|banner|border|invite|accept|transfer>
    aliases: [t]
  tw:
    description: Send a message to your team.
    usage: /tw <message>
    aliases: [tm, teammsg, tsay, tmsg]
  tc:
    description: Toggle team chat mode on or off.
    usage: /tc
    aliases: [tchat, tctoggle, teamchat]
  token:
    description: Admin command for managing Soul Tokens
    usage: /token give <player> <amount>
    permission: soulsmp.admin
    aliases: [st, stoken, soultoken]
  journal:
    description: Opens the Fishing Journal
    usage: /journal
    aliases: [ fj, fishingjournal ]
  fishsim:
    description: Simulate fish generation and print score statistics + sell multiplier suggestions.
    usage: /fishsim [samples] [luck]
  lb:
    description: Leaderboard admin
    usage: /lb <set|remove|recompute>
    permission: soulsmp.admin
  stuck:
    description: Kill yourself if you are stuck
    usage: /stuck
  koth:
    description: King of the Hill (prepare/join/start)
    usage: /koth <x> <y> <z> | /koth join | /koth leave | /koth start | /koth stop | /koth status
  voucher:
    description: Give vouchers (name tags) that upgrade a team.
    usage: /voucher give <player> <type> [amount] [extra] [count]
    permission: soulsmp.admin
  opmode:
    description: Toggle creative op mode with inventory/xp/location snapshot.
    usage: /opmode
  reboot:
    description: Reboot the server with a countdown
    permission: soulsmp.reboot

permissions:
  soulsmp.opmode:
    default: op

